### PR TITLE
Fix thumbnail size.

### PR DESCRIPTION
**Pull request by rdoeffinger**
Currently they are just one big blurry mess,
due to them being 1/10th the size of full resolution
it seems.

Signed-off-by: Reimar Döffinger Reimar.Doeffinger@gmx.de

### CODE REVIEW

**Comment by rdoeffinger** [comment]
I realized that I don't really know what the intent was.
However I think with the second patch it matches how density was intended to be used from Android size.
And it seems to work fairly well, and definitely better than before across a large span of device sizes (though on a laptop/desktop screen a larger size might make sense as it seems unlikely anyone would have 100s of maps, but it's still better than the old code that would use huge thumbnails so just 2 or so would fit).
The first patch probably would be more correct without the multiplication with density too though.

**Comment by diedricm** [comment]
That looks much better ... to be honest I never really understood that strange if/else construction before ...

Sorry for my inactivity at the moment ... currently have lots of exams :/

**Comment by rdoeffinger** [comment]
Yeah, I suspected it would be exam time. While like most people I am fairly good at being impatient, there is no particular hurry really. The patches won't run away ;)

**Comment by diedricm** [comment]
It looks good. Could you rebase this, or give me a tip how I can merge this?

**Comment by rdoeffinger** [comment]
Nothing tricky really, the removed variable just conflicted with the added intentPos from the geo: support.
Pushed a rebased version.

**Pull request merged**
