### PR TITLE
Load thumbnail instead of full image.

### PR DESCRIPTION
**Pull request by rdoeffinger**
This should reduce the number of OOM crashes a lot.

Signed-off-by: Reimar Döffinger Reimar.Doeffinger@gmx.de

### CODE REVIEW

**Comment by diedricm** [comment]
Good catch but the whole second if/else part sill makes no real sense. Shouldn’t it basically work like this?

``` java
if (thumbFile.exists()) {
    thumbBitmap = BitmapFactory.decodeFile(thumbFile.getAbsolutePath());
} else {
    thumbBitmap = BitmapFactory.decodeResource(resources, R.drawable.map_dummy));
}
bitmapList.add(thumbBitmap);
```

**Comment by rdoeffinger** [comment]
I think it makes sense, it checks in the first if whether the thumbnail exists and the second if checks if it can be loaded/decoded.
If anything the .exists() check probably could go away as I'd expect decodeFile will just fail in that case, too.
But I updated the patch to not uselessly read and decode it a second time.

**Comment by rdoeffinger** [comment]
(as an aside in principle doing a .exists() check is basically always a time-of-check-time-of-use race condition and thus a bad idea, but as it should be harmless here and I don't feel like testing this thoroughly I'd rather keep the changes minimal)

**Comment by diedricm** [comment]
Ahh yes of course ... thank you.

**Pull request merged**
