### PR TITLE
Gradle support

### PR DESCRIPTION
**Pull request by rdoeffinger**
Adds gradle files and some other stuff AndroidStudio wants.
Should make it easier for people to get started with the project, in particular getting rid of magic steps like "copy the appcompat directory from the SDK to the checkout directory" etc.
Still not happy about the buildsystem crapping its files all over the place though.

### CODE REVIEW

**Comment by diedricm** [comment]
I know that easier building would be nice, but I know very little about all these files android-studio generates. It might be better to include a simple shell script and git-submodule so that we can include/build appcompat and opencv that way. It already works like that for the fdroid build. The manifest can be found here: https://gitlab.com/diedricm/fdroiddata/blob/master/metadata/de.hu_berlin.informatik.spws2014.mapever.txt

**Comment by rdoeffinger** [comment]
The release tarball that F-Droid uses contains a build.xml which is not in git either and seems to be used together with ant.
Gradle, just like ant is just a build-system, and one supported by F-Droid as well. But it also supports automatic dependency handling. And AndroidStudio understands it and can parse it.
It only needs 3 files: MapEver/build.gradle, build.gradle and settings.gradle.
The gradlew stuff is helper scripts/code to get and start gradle in an appropriate version (which I just realize doesn't work in my patch).
It can reference the appcompat from the SDK on its own, so no script should be needed there.
And I am not sure there is a one-size-fits-all way to handle building OpenCV.
IMHO at least the minimal 3 files provide an acceptable repository litter vs usefulness ratio.
Maybe you can consider integrating the minimal version I changed this pull request to.

**Comment by diedricm** [comment]
Tested this branch with android-studio right now and it somehow cannot find appcompat. Will try later again, as I never really worked with IntelliJ/Graddle before ...

**Comment by rdoeffinger** [comment]
It may be less intelligent than I thought, I had from the start "Extras/Android Support Library" installed via the SDK manager.
It definitely should be able to pick up that one.

**Comment by diedricm** [comment]
Okay this time it worked after it downloaded some gradle files ... strange. The native opencv libs will still need to be put into the libs file manually, but that’s the same for the eclipse adt files.

**Pull request merged**
